services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./mysql/02_CreateRoom.sql:/docker-entrypoint-initdb.d/02_CreateRoom.sql
      - ./mysql/03_DeleteById.sql:/docker-entrypoint-initdb.d/03_DeleteById.sql
      - ./mysql/04_FindById.sql:/docker-entrypoint-initdb.d/04_FindById.sql
      - ./mysql/05_UpdateRoom.sql:/docker-entrypoint-initdb.d/05_UpdateRoom.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: raw-spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mysql:3306/app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_pass
    depends_on:
      - mysql

volumes:
  mysql_data:
